// <auto-generated />
using System;
using BasicBackendTemplate.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BasicBackendTemplate.Migrations
{
    [DbContext(typeof(BasicBackendTemplateContext))]
    [Migration("20240817184554_AddModulesPropoerties")]
    partial class AddModulesPropoerties
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BasicBackendTemplate.Models.Module", b =>
                {
                    b.Property<int>("IdModule")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdModule"));

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("module_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("visibilityStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdModule")
                        .HasName("PK__Module__9D5F9CEB3D4CC0BF");

                    b.ToTable("Modules", (string)null);
                });

            modelBuilder.Entity("BasicBackendTemplate.Models.Permiso", b =>
                {
                    b.Property<int>("PermisoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermisoId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("PermisoId")
                        .HasName("PK__Permiso__96E0C723B9F1774B");

                    b.ToTable("Permiso", (string)null);
                });

            modelBuilder.Entity("BasicBackendTemplate.Models.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("RolId")
                        .HasName("PK__Rol__F92302F1BC274A1A");

                    b.ToTable("Rol", (string)null);
                });

            modelBuilder.Entity("BasicBackendTemplate.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId")
                        .HasName("PK__Usuarios__2B3DE79801DD5826");

                    b.HasIndex(new[] { "Email" }, "UQ__Usuarios__A9D10534029CD87A")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("RolPermiso", b =>
                {
                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<int>("PermisoId")
                        .HasColumnType("int");

                    b.HasKey("RolId", "PermisoId")
                        .HasName("PK__RolPermi__D04D0E83B555BC8B");

                    b.HasIndex("PermisoId");

                    b.ToTable("RolPermiso", (string)null);
                });

            modelBuilder.Entity("UsuarioRol", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId", "RolId")
                        .HasName("PK__UsuarioR__24AFD797599EC1E0");

                    b.HasIndex("RolId");

                    b.ToTable("UsuarioRol", (string)null);
                });

            modelBuilder.Entity("RolPermiso", b =>
                {
                    b.HasOne("BasicBackendTemplate.Models.Permiso", null)
                        .WithMany()
                        .HasForeignKey("PermisoId")
                        .IsRequired()
                        .HasConstraintName("FK__RolPermis__Permi__2739D489");

                    b.HasOne("BasicBackendTemplate.Models.Rol", null)
                        .WithMany()
                        .HasForeignKey("RolId")
                        .IsRequired()
                        .HasConstraintName("FK__RolPermis__RolId__2645B050");
                });

            modelBuilder.Entity("UsuarioRol", b =>
                {
                    b.HasOne("BasicBackendTemplate.Models.Rol", null)
                        .WithMany()
                        .HasForeignKey("RolId")
                        .IsRequired()
                        .HasConstraintName("FK__UsuarioRo__RolId__2B0A656D");

                    b.HasOne("BasicBackendTemplate.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK__UsuarioRo__Usuar__2A164134");
                });
#pragma warning restore 612, 618
        }
    }
}
