// <auto-generated />
using System;
using LotteryServices.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LotteryServices.Migrations
{
    [DbContext(typeof(LoteriaDbContext))]
    partial class LoteriaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LotteryServices.Models.Boleto", b =>
                {
                    b.Property<int>("BoletoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BoletoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BoletoId"));

                    b.Property<DateTime?>("FechaCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("SorteoId")
                        .HasColumnType("int")
                        .HasColumnName("SorteoID");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    b.HasKey("BoletoId")
                        .HasName("PK__Boletos__C5AF44348C3A30AB");

                    b.HasIndex("SorteoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Boletos");
                });

            modelBuilder.Entity("LotteryServices.Models.NumerosBoleto", b =>
                {
                    b.Property<int>("NumeroBoletoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NumeroBoletoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NumeroBoletoId"));

                    b.Property<int>("BoletoId")
                        .HasColumnType("int")
                        .HasColumnName("BoletoID");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.HasKey("NumeroBoletoId")
                        .HasName("PK__NumerosB__CF017B1BAA2D14AC");

                    b.HasIndex("BoletoId");

                    b.ToTable("NumerosBoletos");
                });

            modelBuilder.Entity("LotteryServices.Models.NumerosSorteo", b =>
                {
                    b.Property<int>("NumeroSorteoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NumeroSorteoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NumeroSorteoId"));

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int>("SorteoId")
                        .HasColumnType("int")
                        .HasColumnName("SorteoID");

                    b.HasKey("NumeroSorteoId")
                        .HasName("PK__NumerosS__C7283F19987C77E6");

                    b.HasIndex("SorteoId");

                    b.ToTable("NumerosSorteos");
                });

            modelBuilder.Entity("LotteryServices.Models.Sorteo", b =>
                {
                    b.Property<int>("SorteoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SorteoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SorteoId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("FechaSorteo")
                        .HasColumnType("datetime");

                    b.HasKey("SorteoId")
                        .HasName("PK__Sorteos__78DF2ECD65F4C8D8");

                    b.ToTable("Sorteos");
                });

            modelBuilder.Entity("LotteryServices.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId")
                        .HasName("PK__Usuarios__2B3DE79801DD5826");

                    b.HasIndex(new[] { "Email" }, "UQ__Usuarios__A9D10534029CD87A")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("LotteryServices.Models.Boleto", b =>
                {
                    b.HasOne("LotteryServices.Models.Sorteo", "Sorteo")
                        .WithMany("Boletos")
                        .HasForeignKey("SorteoId")
                        .IsRequired()
                        .HasConstraintName("FK__Boletos__SorteoI__3F466844");

                    b.HasOne("LotteryServices.Models.Usuario", "Usuario")
                        .WithMany("Boletos")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK__Boletos__Usuario__3E52440B");

                    b.Navigation("Sorteo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LotteryServices.Models.NumerosBoleto", b =>
                {
                    b.HasOne("LotteryServices.Models.Boleto", "Boleto")
                        .WithMany("NumerosBoletos")
                        .HasForeignKey("BoletoId")
                        .IsRequired()
                        .HasConstraintName("FK__NumerosBo__Bolet__4222D4EF");

                    b.Navigation("Boleto");
                });

            modelBuilder.Entity("LotteryServices.Models.NumerosSorteo", b =>
                {
                    b.HasOne("LotteryServices.Models.Sorteo", "Sorteo")
                        .WithMany("NumerosSorteos")
                        .HasForeignKey("SorteoId")
                        .IsRequired()
                        .HasConstraintName("FK__NumerosSo__Sorte__44FF419A");

                    b.Navigation("Sorteo");
                });

            modelBuilder.Entity("LotteryServices.Models.Boleto", b =>
                {
                    b.Navigation("NumerosBoletos");
                });

            modelBuilder.Entity("LotteryServices.Models.Sorteo", b =>
                {
                    b.Navigation("Boletos");

                    b.Navigation("NumerosSorteos");
                });

            modelBuilder.Entity("LotteryServices.Models.Usuario", b =>
                {
                    b.Navigation("Boletos");
                });
#pragma warning restore 612, 618
        }
    }
}
